### ISSUE TITLE
Processing of IPv6 packets

### ISSUE THREAD

**Issue by dlrobertson** [smoltcp-rs/smoltcp#103]
Now that #76 has been completed we can now move on to the handling of IPv6 packets. This metabug details the roadmap to add processing of IPv6 packets to smoltcp.
 
- Additions to `wire`
   - [x] [ICMPv6] (PR #128)
   - [x] [MLDv2] (PR #252)
   - [x] [NDISC] (PRs #167 #191 )
   - [x] Handle extension headers
       - [x] Add [IPv6] `Options` (PR #125)
       - [x] Add [IPv6] `Hop-by-Hop` extension header (PR #139)
       - [x] Add [IPv6] `Routing` extension header (PR #218)
       - [x] Add [IPv6] `Fragment` extension header (PR #168)
   - [x] Add [IPv6] `No Next` header
 - Updates to `socket`
   - [x] Update `IcmpSocket` to also handle [ICMPv6] packets (Issue #99 PR #205)
   - [x] Update `RawSocket` to also handle [IPv6] packets (PR #118) 
 - Updates to `iface`
   - [x] Enable `deny(unused)` when `proto-ipv6` is enabled, but `proto-ipv4` is not. (PR #121)
   - [x] Correctly handle [IPv6] packets, forwarding packets to the `accept`ing socket. (PR #121)
   - [x] Add Address Resolution via [NDISC] (PR #196)

Related to: #3

[ICMPv4]: https://tools.ietf.org/html/rfc792
[ICMPv6]: https://tools.ietf.org/html/rfc4443
[IPv6]: https://tools.ietf.org/html/rfc8200
[MLDv2]: https://tools.ietf.org/html/rfc3810
[NDISC]: https://tools.ietf.org/html/rfc4861\
[ADDRARCH 2.7.1]: https://tools.ietf.org/html/rfc4291#section-2.7.1

**Comment by dlrobertson** [comment]
The very first PR should probably just handle IPv6 packets and forward them to the socket. The second should probably handle sending packets via `RawSocket`. After those are done then we can begin to tacke address resolution etc.
 
For a first pass at extension headers it may be worthwhile to add the extension headers to `wire` but only handle the `Pad1` and `PadN` options. Discarding packets with options according to the options type [RFC 8200 4.2]

[RFC 8200 4.2]: https://tools.ietf.org/html/rfc8200#section-4.2

**Comment by whitequark** [comment]
:+1:

**Comment by hjr3** [comment]
@dlrobertson let me know what help you need, if any, on this.

**Comment by dlrobertson** [comment]
The two next big steps will be to add the following two packet types to `wire`.

 - ICMPv6
 - Extension headers (start with just the `Pad1` and `PadN` `Options`)

Both of which are a bit of a quest. I've just started on ICMPv6 support, so I'd suggest working on extension headers (However, if you're an ICMPv6 wizard or dead set on working on it I'm okay with pivoting to Extension Headers). #99 is also another great issue that is related to this, but it might be better to do #99 post ICMPv6 support.

If you need some pointers, feel free to ping me as `dlrobertson` on the `freenode` `#m-labs` channel or the [Redox OS chat]. I'm definitely a bit more active on the [Redox OS chat] `#networking` channel, but @whitequark is also available on the `freenode` `#m-labs` IRC channel.

[Redox OS chat]: https://github.com/redox-os/book/blob/master/src/contributing/chat.md

**Comment by hjr3** [comment]
@dlrobertson I will start on the extension headers.

**Comment by dlrobertson** [comment]
Awesome! I definitely appreciate the help

**Comment by hjr3** [comment]
@dlrobertson I have not been able to catch you on #m-labs irc and I just requested access to redox chat. I have started working on the `Hop-by-Hop Options Header` implementation at https://tools.ietf.org/html/rfc8200#section-4.3.

**Comment by dlrobertson** [comment]
Still a lot more to be done, but #252 was the last issue that was part of this.
