### ISSUE TITLE
Add IPv6 to wire

### ISSUE THREAD

**Issue by dlrobertson** [smoltcp-rs/smoltcp#76]
- [x] Make IPv4 optional by adding a feature gating it. #98 
 - [x] Add Ipv6Address/Ipv6Cidr. #72 
 - [x] Add Ipv6Packet/Ipv6Repr. #89 

Metabug from https://github.com/m-labs/smoltcp/pull/72#issuecomment-342369380.

Related to #3
