### ISSUE TITLE
Tracking issue for RPL

### ISSUE THREAD

**Issue by thvdveld** [smoltcp-rs/smoltcp#769]
I create this tracking issue for the RPL support (instead of 1 big PR #627) [RFC6550](https://datatracker.ietf.org/doc/html/rfc6550). 

- [x] https://github.com/smoltcp-rs/smoltcp/pull/766
- [x] https://github.com/smoltcp-rs/smoltcp/pull/781 replacing
  - [ ] ~~https://github.com/smoltcp-rs/smoltcp/pull/765~~
  - [ ] ~~https://github.com/smoltcp-rs/smoltcp/pull/770~~
- [x] https://github.com/smoltcp-rs/smoltcp/pull/767
- [x] https://github.com/smoltcp-rs/smoltcp/pull/772
- [x] https://github.com/smoltcp-rs/smoltcp/pull/773
- [x] https://github.com/smoltcp-rs/smoltcp/pull/777
- [x] https://github.com/smoltcp-rs/smoltcp/pull/790
- [x] https://github.com/smoltcp-rs/smoltcp/pull/798 (Objective Function Zero [RFC6552](https://datatracker.ietf.org/doc/html/rfc6552) and preferred parent set)
- [x] https://github.com/smoltcp-rs/smoltcp/pull/829 (for RPL Hop-by-hop and source routing header support)
- [ ] Mode of operation 0: no downward routes maintained
- [ ] Mode of operation 1: upward routes, without storing mode
- [ ] Mode of operation 2: upward routes, with storing (without broadcast)
- [ ] Mode of operation 3: upward routes, with storing (with broadcast)
